
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RBRACK = 24;
  public static final int TIMES = 10;
  public static final int LT = 12;
  public static final int ELSE = 3;
  public static final int NOTEQ = 17;
  public static final int PLUS = 8;
  public static final int RPAREN = 22;
  public static final int INT = 4;
  public static final int LTE = 13;
  public static final int SEMI = 19;
  public static final int WHILE = 7;
  public static final int LBRACK = 23;
  public static final int RETURN = 5;
  public static final int IF = 2;
  public static final int LPAREN = 21;
  public static final int GT = 14;
  public static final int ID = 27;
  public static final int GTE = 15;
  public static final int NUM = 28;
  public static final int LSQBRACK = 25;
  public static final int RSQBRACK = 26;
  public static final int COMMA = 20;
  public static final int EOF = 0;
  public static final int DIVIDE = 11;
  public static final int MINUS = 9;
  public static final int error = 1;
  public static final int ASSIGN = 18;
  public static final int EQ = 16;
  public static final int VOID = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "INT",
  "RETURN",
  "VOID",
  "WHILE",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LT",
  "LTE",
  "GT",
  "GTE",
  "EQ",
  "NOTEQ",
  "ASSIGN",
  "SEMI",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "LSQBRACK",
  "RSQBRACK",
  "ID",
  "NUM"
  };
}

